trydjango19-append - Copy (2)/posts/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
from django.conf.urls import handler404,handler400


urlpatterns = [
    url(r'^$', views.post_list,name="list"),
    url(r'^ajax-posts/$', views.post_ajax,name='ajax'),
    url(r'^drafts/$',views.drafts,name="drafts"),
    url(r'^create/$', views.post_create),
    url(r'^(?P<slug>[\w-]+)/$', views.post_detail,name="detail"),
    url(r'^(?P<slug>[\w-]+)/edit$', views.post_update,name='update'),
    url(r'^(?P<slug>[\w-]+)/delete$', views.post_delete,name="delete"),


    #url(r'^user/',views.userAuth,name = "userauth")

]


trydjango19-append - Copy (2)/posts/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from django.utils import timezone
import uuid
from markdown_deux import markdown
from django.utils.safestring import mark_safe
from django.core.validators import *


# Create your models here.
# MVC
class PostManager(models.Manager):
    def active(self,*args,**kwargs):
        return super(PostManager,self).filter(draft=False).filter(publish__lte = timezone.now())
    def drafts(self):
        return super(PostManager,self).filter(draft=True).filter(publish__gte=timezone.now())
def upload_location(instance,filename):
    print("%s/%s"%(instance.slug,filename))
    return "%s/%s"%(instance.slug,filename)

class Post(models.Model):
    #uuid = models.UUIDField(default=uuid.uuid4,editable=False,unique=True) this field gives a unique id id but iam usinh slugs vecause it is giving migration error
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False,auto_now_add=False,default=None)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,default=1)
    slug = models.SlugField(unique=True)
    title = models.CharField(max_length=120)
    image = models.ImageField(upload_to=upload_location,
                              null=True,blank=True,
                              width_field="width_field",
                              height_field="height_field",

                              )
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    views = models.PositiveIntegerField(default=0)
    comments = models.PositiveIntegerField(default=0)
    objects = PostManager()

    def __str__(self):
        return self.slug

    def clean_fields(self,*args,**kwargs):
        if self.draft is True :
            if self.publish <timezone.now().date():
                raise ValidationError({'publish': ["Must be louder!", ]})

    def get_absolute_url(self):
        #print("hhahahahahahhahahhahahahaha")
        return reverse("posts:detail",kwargs={"slug":self.slug})

    class Meta: # this will display ecent posts first
        ordering = ["-timestamp", "-updated"]

# def create_slug(instance,buffer=0,new_slug=None):
#     slug = slugify(instance.title)  #SlugTesting
#     s = slugify(instance.title)
#     if new_slug is not None:
#         slug = new_slug  #SlugTesting
#         if (buffer>0):
#             slug = "%s-%s"%(slug,buffer)
#
#     qs = Post.objects.filter(slug=slug).order_by("-id")
#     exits=qs.exists()
#     if exits:
#         buffer+=1
#         return create_slug(instance,buffer,new_slug=s)
#     return slug

    def get_markdown(self):
        content = self.content
        md =  markdown(content)
        return mark_safe(md)


def create_slug(instance):
    buffer=1
    slug = slugify(instance.title)
    qs = Post.objects.filter(slug=slug).order_by("-id")
    if qs.exists():

        while True:
            s=slug
            s="%s-%s"%(s,buffer)
            qs = Post.objects.filter(slug=s).order_by("-id")
            if  not qs.exists():
                return s
            buffer+=1
    return slug



def pre_post_save_reciever(sender,instance,*args,**kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_post_save_reciever,sender=Post)

trydjango19-append - Copy (2)/posts/forms.py
from django import forms
from  .models import Post
from pagedown.widgets import PagedownWidget
from django.core.validators import *
from django.utils import timezone
from bootstrap_datepicker.widgets import DatePicker


class PostForm(forms.ModelForm):
    publish = forms.DateField(widget=forms.SelectDateWidget)
    content = forms.CharField(widget=PagedownWidget(show_preview=False))
    draft = forms.BooleanField
    image = forms.FileField


    def clean_image(self):

        image = self.cleaned_data.get('image', False)
        if image:
            if image._size > 8 * 1024 * 1024:
                raise ValidationError("Image file too large ( > 4mb )")
            return image
        else:
            image ="#"
        return image


    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "image",
            'draft',
            'publish'

        ]

trydjango19-append - Copy (2)/posts/views.py
from django.shortcuts import render,get_object_or_404,redirect,render_to_response
from django.http import HttpResponse, HttpResponseRedirect, Http404, request,HttpResponsePermanentRedirect
from django.contrib.contenttypes.models import ContentType
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from urllib.parse import quote_plus
from django.utils import timezone
import json
from .models import Post
from .forms import PostForm
from comments.models import Comment


# Create your views here.

def url_redirect(request):
    return HttpResponsePermanentRedirect("/posts/")

def post_create(request):
    if not request.user.is_staff and not request.user.is_superuser:
        raise Http404
    form = PostForm(request.POST or None,request.FILES or None )
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user

        instance.save()
        if form.errors:
            messages.error(request,"Form not submitted",extra_tags="success")
        messages.success(request,"Form Submitted")
        return HttpResponseRedirect(instance.get_absolute_url())


    context = {
        "form":form
    }
    return render(request,"post_form.html",context)


def post_detail(request, slug):

    instance = get_object_or_404(Post,slug=slug)
    if instance.publish > timezone.now().date()or instance.draft:
        if not request.user.is_superuser and not request.user.is_staff:
            raise Http404
    content_type = ContentType.objects.get_for_model(Post)
    obj_id = instance.id
    instance.views+=1
    instance.save()
    comments = Comment.objects.filter(content_type=content_type,object_id=obj_id)
    context ={
        'title':instance.title,
        'instance':instance,
        'comments':comments,

    }
    return render(request,"detail.html",context)


def post_list(request):
    ip = get_clientIp(request)

    context = {

        'title':'List',

        'ip':ip,
    }
    return render(request, "post_list.html",{})

def post_ajax(request):

    TOTAL = 3
    offset = int(request.GET.get('offset', 0))
    END = int(offset) + int(TOTAL)
    articles = Post.objects.all()[offset:END]
    qs = Post.objects.all()[END:END+3]


    context ={
        'qs':articles
    }
    if qs.__len__()==0:
        return HttpResponse('false')

    return render_to_response("paginated_posts.html", context,)

def post_update(request,slug=None):

    if not request.user.is_authenticated():
        raise Http404
    if not request.user.is_superuser:
        if request.user.is_staff:
            instance = get_object_or_404(Post, slug=slug)
            if not instance.user == request.user:
                raise Http404
    instance = get_object_or_404(Post,slug=slug)
    form = PostForm(request.POST or None,request.FILES or None,instance=instance,)
    if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            messages.success(request,"post Updated")
            return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        'title':instance.title,
        'instance':instance,
        'form':form,
    }
    return render(request,"post_form.html",context)




def post_delete(request ,slug):
    instance = get_object_or_404(Post,slug=slug)
    if not request.user.is_superuser:
        if not request.user == Post.user:
            raise Http404
    instance.delete()
    messages.success(request,"Post successfully deleted",extra_tags="warning")

def drafts(request):

    page_var = "page"
    if request.user.is_superuser:
        queryset_list = Post.objects.drafts()
    elif request.user.is_staff:
        queryset_list = Post.objects.filter(draft=True).filter(publish__gte=timezone.now().date()).filter(user=request.user)
    else:
        raise Http404
    paginator = Paginator(queryset_list, 7)  # Show 25 contacts per page

    page = request.GET.get(page_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)

    context = {
        'object_list': queryset,
        'title': 'List',
        'page_var': page_var
    }
    return render(request, "post_list.html", context)


def error404(request):
    return render(request,"404.html",{})
def error400(request):
    return render(request,"500.html",{})


def get_clientIp(request):
    """get the client ip from the request
    """
    ip= request.META['REMOTE_ADDR']
    return ip

trydjango19-append - Copy (2)/templates/ajax.html
{% extends 'base.html' %}
{% block content %}
    <style>
    {% block style_block %}
        #ArticlesDiv {
            height: 10000px;
            position: absolute;
        }
    {% endblock %}
    </style>
    <!-- All articles will be loaded in following div -->
<div id="ArticlesDiv"></div>
    <script>
        var postOffset =0;
        ArticleLoader();

        console.log("postOffset");
        function ArticleLoader () {
            url1  = '{{ request.build_absolute_uri }}ajax-posts/?offset='+postOffset;

            $.ajax({
                url: url1,
                dataType: 'html',
                success: function (data) {
                    console.log(data)
                    $("#ArticlesDiv").append(data);
                    postOffset+=10;
                    console.log(postOffset)
                }

            })
        }
        var $window = $(window);
            $(document).scroll(function prodScrollPosition() {
                var distance = $window.scrollTop() + $window.height();
                if ($(window).scrollTop() >= $(document).height() - $(window).height() - 108) {
                    console.log($window.height);
                    ArticleLoader()
                }
            })

    </script>
{% endblock %}

trydjango19-append - Copy (2)/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
       <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <meta charset="UTF-8">
        <title>{% block head %}Try Django 1.9 {% endblock head %}</title>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" >
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
        <link rel="stylesheet" href="{% static 'css/styles2.css' %}">
        <link rel="stylesheet" href="{% static 'css/ionicons.css' %}">
        <link rel="stylesheet" href="{% static 'css/swiper.css' %}">

        <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.12/marked.js"></script>
        <style>
            {% block style_block %}{% endblock style_block %}
        </style>
        {% block extraHead %}{% endblock extraHead %}
        </head>
    <body>

    <nav>
		<div class="logo">LOGO</div>
			<ul>
				<li><a href="">home</a></li>
				<li><a href="">user</a></li>
				<li><a href="">blog</a></li>
				<li><a href=""class="active">contact us</a></li>
			</ul>

	</nav>
       {% include "messages_display.html" %}
        <div class="kk" >
            {%if request.user %}

        {% endif %}
            {% block content %}{% endblock content %}
        </div>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    </body>
    {% block script2 %}{% endblock script2%}
    <script>
        $(window).on('scroll',function  () {
        if($(window).scrollTop()) {
          $('nav').addClass("black")
        }else{
          $('nav').removeClass("black")
        }
      })
    </script>
<link rel="stylesheet" href="{% static 'css/base.css' %}">

</html>


trydjango19-append - Copy (2)/templates/detail.html

{% extends "base.html" %}
{% load urlify %}
{% block head %}
    {{ instance.title }} | {{ block.super }}
{% endblock head %}
{% block content %}
    <div class="col-sm-6 col-sm-offset-3 ">

        {% if instance.image %}
        <img src={{ instance.image.url }} class="img-responsive alt="">
        {% endif %}

        <h1>{{ title }} <small> {% if instance.draft %} <span style="color: red">Draft</span>{% endif %} {{ instance.publish}}.</small></h1>
        {% if instance.image %}

        {% endif %}

        <p>Author:{{ instance.user.get_full_name }}</p>
    <p>
    <div class="fb-like" data-width=""></div>
   <div class = "res-img"> <p>{{ instance.get_markdown}}<br></p></div>
        <hr>
    <div>
        <p class="lead">Comments:</p>
            {% for foo in comments %}
                <div>
                    {{ foo.content  }}
                    <br>
                    <small>{{ foo.user }} | {{ foo.timestamp|timesince }} ago</small>
                    <hr>
                </div>
            {% endfor %}

    </div>

















    <!--FaceBook-->
        <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">
         Facebook
        </a>
    <!--Twitter-->
        <a href="https://twitter.com/home?status={{ instance.content|urlify }}{{ request.build_absolute_uri }}">
        - Twitter
        </a>
    <!--GooglePlus-->
        <a href='https://plus.google.com/share?url={{ request.build_absolute_uri }}'>- GooglePlus</a>

    <!--LinkedIn-->
        <a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}&title={{ instance.title }}&summary={{ instance.content|urlify }}&source={{ request.build_absolute_uri }}">
            - Linkedin
        </a>
    <!--Reddit-->
        <a href="http://www.reddit.com/submit?url={{ request.build_absolute_uri }}&title={{ instance.title }}">- Reddit</a>

    </div>
{% endblock content %}
<style>


{% block style_block %}
    img{
        padding-top: 10px;
    }
{% endblock style_block %}
</style>

trydjango19-append - Copy (2)/templates/messages_display.html
 {% if messages %}
        <div class="messages">
        <div class="container">

            <ul class="messages">
                {% for message in messages %}
                    <div class="alert  alert-{{ message.tags|safe }} borderr">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        {{ message }}
                    </div>
                {% endfor %}
            </ul>
            </div>
        </div>
    {% endif %}

trydjango19-append - Copy (2)/templates/paginated_posts.html
{% load staticfiles%}
{% for obj in qs %}
                <div class="row">

                <div class="col-lg-4 col-md-6">
                    <div class="card h-100">
                        <div class="single-post post-style-1">

                            <div class="blog-image"><img src="{{ obj.image.url }}" alt="Blog Image"></div>

                            <a class="avatar" href="#"><img class="img-responsive" src="{% static 'images/dumyavatar.jpg'%}" alt="Profile Image"></a>

                            <div class="blog-info">

                                <h4 class="title"><a class = "contt" href='{{ obj.get_absolute_url }}'><b>{{ obj.get_markdown }}</b></a></h4>

                                <ul class="post-footer">
                                    <li><a href="#"><i class="ion-heart"></i>57</a></li>
                                    <li><a href="#"><i class="ion-chatbubble"></i>{{ obj.comments }}</a></li>
                                    <li><a href="#"><i class="ion-eye"></i>{{ obj.views }}</a></li>
                                </ul>

                            </div><!-- blog-info -->
                        </div><!-- single-post -->
                    </div><!-- card -->
                </div>
{% endfor %}
<!-- <div class="row">
    <div class="col-sm-12">
        <div class="thumbnail">
            {% if obj.image %}
            <img src={{ obj.image.url }} class="img-responsive alt="">
            {% endif %}
            <div class="caption res-img">
                <h3><a href='{{ obj.get_absolute_url }}'>{{ obj.slug }} </a><span>{% if obj.draft %} <span style="color:red;">Draft  </span></span>{% endif %}{{ obj.timestamp|timesince }} ago</small></h3>
                <p>Author: {{ obj.user }}</p>
                <p class = "content-markdown">{{ obj.get_markdown|truncatechars_html:150}}</p>
                <p><a href="{{obj.get_absolute_url}}" class="btn btn-primary" role="button">View</a></p>
            </div>
        </div>
    </div>
    <hr>
</div> -->

trydjango19-append - Copy (2)/templates/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block extraHead %}{{ form.media }}{% endblock %}
{% block content %}

    <div class="container">
        <div class="col-sm-6">
            <div class="thumbnail" style="min-height: 300px;">
                <h1 style="text-align: center;margin-top: 0;">Preview:</h1>
                <div class="content-preview">
                    <h3 id="preview-title">
                        <h1></h1>
                    </h3>
                    <p id="preview-content"></p>
                </div>
            </div>
        </div>
        <div class="col-sm-6 thumbnail " style="">
        <h1>Form</h1>
        <form method="POST" enctype="multipart/form-data">{% csrf_token %}

            {{ form|crispy }}
            <input type="submit"value="Create Post" class="btn btn-default"/>
        </form>
        </div>
    </div>
{% endblock content %}
{% block script2 %}
    <script>
        $(document).ready(function () {

            $(".res-img img").each(function () {
                $(this).addClass("img-responsive")
            });
            //title
            var titleInput=$("#id_title");

            //content
            var contentInput =$("#id_content");
            setContent(contentInput.val());
            contentInput.keyup(function () {
                var newContent = $(this).val();
                setContent(newContent);
            });

            function setContent(value) {
                var markedContent = marked(value);
                 $("#preview-content").html(markedContent);
                 $("#preview-content img").each(function () {
                     $(this).addClass("img-responsive");
                 })


            }
            function setTitle(value) {
                $("#preview-title").text(value);
            }
            setTitle(titleInput.val())
            titleInput.keyup(function () {
                setTitle($(this).val());
            })
        })

    </script>
{% endblock script2 %}

trydjango19-append - Copy (2)/templates/post_list.html
{% extends  "base.html" %}

{% block content %}

    <section class="blog-area section">
    <div class="container">
        <div class="cont"></div>
    </div>


    {% block script %}
        <script>

        var postOffset =0;
        var timeout ;
        ArticleLoader();
        ArticleLoader();
        ArticleLoader();

        console.log("postOffset");
        function ArticleLoader () {
            url1  = '{% url "posts:list" %}ajax-posts/?offset='+postOffset;

            $.ajax({
                url: url1,
                dataType: 'html',
                success: function (data) {
                     var reply = data.replace(/\s+/, "");
                    console.log(reply);
                    var dat = $(reply).text();
                    if(reply === 'false'){
                        try {
                            $(document).off();
                            $(".cont").append("<blockquote>No more Posts to Display</blockquote>");
                            data ='';

                        }catch(e) {
                            alert(e)
                        }

                    }

                    $(".cont").append(data);
                    $(".cont img").addClass("img-responsive");


                    postOffset+=3;
                    console.log(postOffset)
                }

            })
        }
        var $window = $(window);
            $(document).scroll(function () {
                clearTimeout(timeout)
                timeout = setTimeout(function () {
                var distance = $window.scrollTop() + $window.height();
                    i=0;
                    if ($(window).scrollTop() >= $(document).height() - $(window).height() - 1000) {
                        console.log($window.height);
                        ArticleLoader();
                        ArticleLoader();


                    }

                },100)
            });

        </script>
    {% endblock script%}






{% endblock content %}